### ISSUE TITLE
account/profile - account create시 동시에 생성되도록 변경

### ISSUE THREAD

**Issue by imn00133** [imn00133/BeerNode#102]
account와 profile작성이 동시에 일어나지 않아 불편함.
이를 한 번에 만들 수 있도록 작성하기

**Comment by jeff8287** [comment]
Multiform을 이용하면 되는듯합니다
https://code1018.tistory.com/244

하지만 역시나 에러가 뜨고..
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'

**Comment by jeff8287** [comment]
(1) 동시 생성 issue
Django의 MultiModelForm을 이용하면 form 두 개를 합칠 수 있다.

아래 라이브러리를 받아준다.

$pip install django-betterforms

그럼 다음과 같은 오류가 뜬다.
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'
betterforms 안의 multiform.py를 보면 django.utils.encoding에서 python_2_unicode_compatible을 import하는데, 이게 django 2.X버전까지만 지원이 된다(확실X)

다음과 같이 수정하자
line 15: from six import python_2_unicode_compatible
line 17: from six.moves import reduce

$pip install django-six

로 six를 설치하면 정상작동된다

(혹시 $pip install django-robots가 필요한지 모르겠음)

출처 : https://code1018.tistory.com/244
https://integer-ji.tistory.com/119
https://django-betterforms.readthedocs.io/en/latest/multiform.html
https://aprkal12-6.tistory.com/2

(2) Fixed: Account 생성시 bootstrap 적용

bootstrap error : Parameter "form" should contain a valid Django Form. 의 문제 해결
출처 : https://stackoverflow.com/questions/34847762/bootstraperror-parameter-form-should-contain-a-valid-django-form
(3) Changed: Profile model의 column 이름 변경; username -> nickname

Account의 username과 동일한 이름을 사용하고 있어 nickname으로 수정

**Comment by jeff8287** [comment]
참고 사이트만 남겨놓고 저는 빤스런..

https://chriskief.com/2012/12/30/django-class-based-views-with-multiple-forms/
https://b0uh.github.io/django-multiple-forms-in-one-class-based-view.html
http://anothercomputingblog.blogspot.com/2010/04/multiple-django-forms-on-same-view.html
http://www.joshuakehn.com/2013/7/18/multiple-django-forms-in-one-form.html
https://krzysztofzuraw.com/blog/2016/two-forms-one-view-django

**Comment by imn00133** [comment]
1. account  생성 후,  nickname 설정하도록 redirection(요즘 많이 사용)
2. login시 없을 경우에도 설정하도록 만들기로 결정됨

- 이거 관련해서 몇 가지 확인하던 게 있어 그 내용을 정리하고 issue를 닫도록 함

**Comment by imn00133** [comment]
https://ssamko.tistory.com/5
-django transaction
