### ISSUE TITLE
account - 회원탈퇴 영어 이름 바꾸기

### ISSUE THREAD

**Issue by imn00133** [imn00133/BeerNode#103]
Quit은 나가기의 느낌 아니냐... 
더 좋은 단어가 없을까?

**Comment by imn00133** [comment]
탈퇴로 변경하고 이슈를 닫자.

**Comment by inhomeENL** [comment]
이거만 탈퇴로 변경하기 좀 그러니 다 바꿔보고 comment/다음 회의 때 별로라면 다시 수정할 예정
