### ISSUE TITLE
scrap app - default 사진 보충

### ISSUE THREAD

**Issue by inhomeENL** [imn00133/BeerNode#121]
- media에 사진이 없어진 경우 사진이 있는 것으로 판단해 default 사진이 뜨지 않음
- 하지만 media에 해당 사진이 없어 불러오지 못함
- 이런 상황도 default 사진이 들어가거나 필요하다면 다른 사진(예를 들어 BeerNode not found라든가 사진증발 등등)

**Comment by kst20209** [comment]
onerror="this.src='{% static 'image/no_img.png' %}'" 속성으로 해결할 수는 있으나, 대체 이미지가 없을 경우에는 무한루프에 빠질 위험이 있다고 합니다.

**Comment by kst20209** [comment]
onerror attribute로 검색하면 결과가 많이 나오네요.

**Comment by imn00133** [comment]
@inhomeENL @kst20209 
https://lhy.kr/django-default-static-image-field
이걸 구성해보면 어떨까? 
대부분은 model에 넣으세요 인데. 이거는 상속받아서 하는거라 괜찮은듯

**Comment by imn00133** [comment]
@kst20209 create 시 경로가 media로 잡힘

**Comment by imn00133** [comment]
왜 고쳐졌는지 알 수 없으나, 현재는 문제가 없어 종료.
