### ISSUE TITLE
시험기간 확인

### ISSUE THREAD

**Issue by imn00133** [imn00133/BeerNode#153]
여러분의 성적을 위해 시험기간은 중지하도록 합시다.
언제인가요?

**Comment by jeff8287** [comment]
- 4/13 선형대수학
- 4/14 농약학
- 4/15 데이터관리와 분석
- 4/22 미생물생화학

**Comment by inhomeENL** [comment]
4/13 통계실
4/27 생물학
4/20 독문이(발표)
4/21 진곤

**Comment by imn00133** [comment]
쭉 잡고, 못 오면 못 오는 걸로 ~4월 3-4주
