### ISSUE TITLE
Scrapapp detail에서 content가 길어지면서 생기는 문제

### ISSUE THREAD

**Issue by kst20209** [imn00133/BeerNode#169]
![image](https://user-images.githubusercontent.com/58202078/113118323-4f43a300-924a-11eb-9c32-b9aea1829540.png)

- table이 길어지는 문제가 생깁니다.

**Comment by inhomeENL** [comment]
#180 
일단 해결은 폭 고정으로 해결했는데
가변적으로 두는 것이 나은지 아니면 보기에 일괄적이도록 고정하는 것이 좋은지 의견 필요
