### ISSUE TITLE
Scrap detail - 맛 관련 코드 압축하기

### ISSUE THREAD

**Issue by jeff8287** [imn00133/BeerNode#171]
scrapapp - detail_table.html에서 맛마다 하드코딩되어있는 부분을 가독성 좋게 수정하기

for flavor in ['sweet', 'sour' ,,, ]
    flavor = getattr(target_beer, flavor)

안 먹히면 view에서 수정하기

**Comment by imn00133** [comment]
view.py
-> kwargs - 값 넘길 수 있음

**Comment by imn00133** [comment]
get_context_data에 원하는 값을 추가해서 던져주면 실행할 수 있음

**Comment by imn00133** [comment]
1. dictionary로 넘겨주기
2. qs.filter를 통해 원하는 column만 넘겨주기
3. getattr을 template에서 사용해서 넘겨주기

**Comment by jeff8287** [comment]
view에서 dictionary로 만들어 get_context_data에서 넘겨준다.
template에서 key, value로 한꺼번에 dictionary를 반복할 때, python에서는 .items()를 사용하나, django template에서는 .items로 한다.
