### ISSUE TITLE
DB - 모델 리팩토링

### ISSUE THREAD

**Issue by inhomeENL** [imn00133/BeerNode#176]
리팩토링의 필요성
- 초기 그냥 만든 모델들을 정리할 필요성
- profile + scraplist 등 mixin과정의 난해함 등

일단 issue를 띄워두고 정확한 내용은 추후 토의 필요

**Comment by imn00133** [comment]
Beer – 맥주 DB
-	유저 평가 평균
-	유저 맛 평가
-	총 평가수
-	위치 – (구매처) / null 가능
-	맥주 사진
-	맥주 meta data
	맥주 이름
	제조 날짜
	양조장
	국가
	장르(라거, 에일 등)
	도수
	맥주 설명
	유저들이 선택한 해시태그를 보여줌(untap)

Scrap – 스크랩 DB
ㄴ writer(User)
ㄴ beer – pk
ㄴ date(마신 날짜)
ㄴ place
ㄴㄴ lng
ㄴㄴ lat
ㄴ context
ㄴ picture
-	사용자가 올렸으면, 올린 사진
-	없을 경우, 맥주 리스트에서 사진 가져오고
-	그것도 없을 경우, default
ㄴ create_at
ㄴ user-pk 구독, 친구 추가 – needs 필요한데, 멀다.
	멀기 때문에 지금 필요하지 않은 듯 함
	절대 평가 값이 없어서 레이팅 가져옴.
	특정 사람의 것이니까 없음
	구독을 해도 그 사람이 쓴 scrap을 보고 싶음
	평가만 보고 싶지는 않음
	스크랩으로 연결은
ㄴ rating
ㄴ sweet
ㄴ sour
ㄴ bitter
ㄴ hoppy
ㄴ fruity
ㄴ malty

Profile – 사용자 DB – User가 들어감
ㄴ user
ㄴ image
ㄴ nickname
ㄴ message

**Comment by imn00133** [comment]
![image](https://user-images.githubusercontent.com/5584872/116783575-60dacd80-aaca-11eb-93d4-7a615c65ef33.png)

**Comment by jeff8287** [comment]
![BeerNode](https://user-images.githubusercontent.com/76732738/117095715-0ed3c980-ada2-11eb-8907-c1a8c0340a52.png)

**Comment by jeff8287** [comment]
image -> multivalued

**Comment by jeff8287** [comment]
Scrap과 Beer 사이에 total participation이 맞을까 의문..
DB에 없는 맥주도 scrap에 beer_name으로 작성할 수 있어야 할텐데, 매우 minor한, 혹은 존재하지 않는 맥주를 적는 경우도 생기게 된다. 
Scrap에 작성한다고 해서 다 DB에 업데이트하면 쓰레기 값을 갖는 맥주들이 생기게 되므로 DB는 그대로 둔다고 하면 partial participation이 맞음

**Comment by imn00133** [comment]
1. 파생된 데이터(별점) 같은 경우, DB에 attribution으로 두지 않고, 그때그때 처리하는 것으로 한다.
- 추후, DB가 작성되고, 데이터 처리 병목이 생기면 view를 활용하여 처리하는 것으로 변경

**Comment by jeff8287** [comment]
![BeerNode](https://user-images.githubusercontent.com/76732738/119252231-08d54980-bbe6-11eb-9e2a-1652e0336217.png)
수정본
