### ISSUE TITLE
News - 메인 화면에 어떤 종류의 소식을 노출할지 토의

### ISSUE THREAD

**Issue by jeff8287** [imn00133/BeerNode#185]
맥주 소식
- 새로 수입된 맥주
- 맥주 토막상식
- 인스타 홍보
- 등등 자유로운 의견 환영

**Comment by imn00133** [comment]
마니아 층을 위한 앱임으로, 첫번째 페이지는 새로 수입된 맥주같은것이 좋을듯
- 토막상식은 로드맵과 더불어서 맥린이(입문자)를 위한 곳에서 작성하는 것이 좋을 것 같음
- 사진 리스트 뷰 형태.

**Comment by imn00133** [comment]
추후 만들기 위해 issue 작성하고 종료
