### ISSUE TITLE
CreateView 개선

### ISSUE THREAD

**Issue by jeff8287** [imn00133/BeerNode#26]
- base.html 상속받아 사용
 - 입력창이 한 줄씩 나오게
 - Model에 Date 추가

**Comment by jeff8287** [comment]
현재 상황
 - base.html 상속받아 사용
 - 입력창이 한 줄씩 나오게
 - git ignore에 media/scrap/ 추가
 - Added: Test template <- 작업하면서 필요해서 만들었는데 영천이가 만들어놔서 필요없어질 예정
    (1) 임시 템플릿에서 Add New Beer 클릭 시 create page로 이동
    (2) create 성공 시 임시 템플릿으로 이동
    (3) db에 저장된 scrap들의 목록 보여줌

ToDo
    (1) 임시 템플릿이 아닌 scrapapplist의 template에 연결하기
    (2) 제목 클릭 시 Detail template으로 연결하기
    (3) Adding a datepicker

**Comment by jeff8287** [comment]
#35
(1) 임시 템플릿이 아닌 scrapapplist의 template에 연결하기
(2) 제목 클릭 시 Detail template으로 연결하기

**Comment by jeff8287** [comment]
#38 
Adding a datepicker
보류.. 혹은 해주실 분 구함

**Comment by imn00133** [comment]
#38 종료에 따라 본 이슈 close
