### ISSUE TITLE
Scraplistapp과 scrapapp 연동

### ISSUE THREAD

**Issue by inhomeENL** [imn00133/BeerNode#35]

**Comment by jeff8287** [comment]
작업중
(1) 임시 템플릿이 아닌 scrapapplist의 template에 연결하기
(2) 제목 클릭 시 Detail template으로 연결하기

**Comment by jeff8287** [comment]
완료
- scraplist/oneline에서 게시글 작성 가능
- 게시글 작성 완료시 scraplist/oneline으로 이동
- scraplist/oneline에 db에 저장된 맥주 목록(이름) 표시
- 맥주 이름 클릭 시 scrap/detail/1로 이동(추후 pk 받아와서 변경 필요)
- scrapapp/test.html 삭제
