### ISSUE TITLE
Scrapplist-scrap 연동(block)

### ISSUE THREAD

**Issue by inhomeENL** [imn00133/BeerNode#43]
block을 살리고자 하는 시도

**Comment by imn00133** [comment]
이게 magicgrid인지는 모르겠지만 암튼.

**Comment by imn00133** [comment]
#51 필요하지 않는 내용이 들어가서 삭제 이슈 열어둠

**Comment by imn00133** [comment]
magic grid.js의 값이 404 not found로 내려오는 것을 확인
- static 관련 설정 확인
  - staticfiles_dirs 설정이 없는 것 확인함
  - 추가후 잘 작동하는 것 확인
자세한 내용은
https://blog.hannal.com/2015/04/start_with_django_webframework_06/
을 참고한다.
