### ISSUE TITLE
ScrapApp - detail-page picture가 없을 때 오류 발생

### ISSUE THREAD

**Issue by imn00133** [imn00133/BeerNode#50]
Error : The 'picture' attribute has no file associated with it.
picture가 null일 경우 표시하지 않도록 수정 필요

**Comment by kst20209** [comment]
{% if target_beer.picture %}
    <img src="{{ target_beer.picture.url }}" alt="맥주 사진" id="profile">
{% endif %}

if 문을 추가해서 수정했습니다. 이 issue가 있었는지 몰랐네요..ㅋㅋㅋㅋ

**Comment by inhomeENL** [comment]
승태가 먼저 수정을 해 놓았지만 해당 부분을 card_blocklist로 빼는 등 변화가 있어 scrapapp의 detail에서 발생하는 문제도 같이 해결해 먼저 PR해 두었음

**Comment by imn00133** [comment]
#65 에서 같이 수정함
