### ISSUE TITLE
scrapapp detail 페이지에서 오류가 발생하는 문제 해결

### ISSUE THREAD

**Issue by kst20209** [imn00133/BeerNode#54]
OperationalError at /scrap/detail/1

no such column: scrapapp_scrap.date

재형이형이 올리고 난 후 pull을 받았는데 runserver에서 이런 문제가 발생하여, 이를 해결하고자 합니다.

**Comment by jeff8287** [comment]
혹시 migration 받아도 안돼?

**Comment by kst20209** [comment]
makemigration만 했어서 해결이 안 되었었는데, migrate로 해결했습니다! :D
