### ISSUE TITLE
Scraplistapp의 필요성에 대해

### ISSUE THREAD

**Issue by inhomeENL** [imn00133/BeerNode#57]
현재 scraplistapp은 createview가 필요 없는 구조인데 scraplistapp을 제거하고 scrapapp에서 list를 구현하는게 맞지 않나 하는 생각이 들어 다음 시간에 토의해볼 필요가 있는듯 합니다

**Comment by imn00133** [comment]
scrap app과 scrap list app의 차이가 무엇인가 라는 질문인가?

**Comment by inhomeENL** [comment]
- 현재는 프로젝트의 크기와 데이터의 크기가 작아 분리의 의미가 크지 않음

- 하지만 후에 현재 자신의 스크랩 말고도 맥주리스트를 보여주는 등 여러 기능 추가
- 이런 기능을 고려해 데이터 리스트를 보여주는 기능으로 설정, 남겨놓자
- = 미래도모

+ scrap app에 다 때려박으면 CRUD에 해당하는 기능이 중복되기 때문에 분리하자
