### ISSUE TITLE
Scrap app: Delete View 만들기

### ISSUE THREAD

**Issue by imn00133** [imn00133/BeerNode#61]
pk를 통해 scrap을 삭제할 수 있도록 작성

**Comment by jeff8287** [comment]
Delete View 추가
detail page에서 삭제 버튼을 통해 게시글 delete 가능해졌는데, 다음과 같은 버그 발생

1) 삭제한 게시글보다 나중에 생성된 게시글의 pk값이 그대로 남아 구멍이 생김
    pk=1,2,3에서 2를 삭제하면 1,3만 남음(scraplist/test의 # column에서 pk만 보여줌)
2) 가장 pk값이 작은 게시글로 접속이 안 됨
    404 error
