### ISSUE TITLE
input type=date를 쓰면 어떨까요?

### ISSUE THREAD

**Issue by kst20209** [imn00133/BeerNode#75]
https://developer.mozilla.org/ko/docs/Web/HTML/Element/Input/date

어떠신가요

**Comment by imn00133** [comment]
나쁘지는 않은데, 사파리가 미지원이긴 하네...

**Comment by kst20209** [comment]
사파리를 버리기는 좀....ㅠㅠㅜ

**Comment by imn00133** [comment]
django내에 widget이 존재하네.
이걸 사용해보는 것으로 하고, issue는 새로 열께.
