### ISSUE TITLE
scraplist - block 비어있는 데이터가 표시되는 문제

### ISSUE THREAD

**Issue by imn00133** [imn00133/BeerNode#81]
1, 2, 3, 4, 5번에 대한 데이터가 없어도 표시되는 문제

**Comment by inhomeENL** [comment]
엥 데이터가 없는데도 block이 뜨는건간요

**Comment by imn00133** [comment]
@inhomeENL ㅇㅇ 1, 2, 3, 4, 5는 뜨던데

**Comment by inhomeENL** [comment]
scrpalistapp - templates - scraplistapp - list.html에 1~5까지 값만 넣어둔게 있었는데 다른 이슈 처리 과정에서 사라짐!
