### ISSUE TITLE
scrap - 맛 추가

### ISSUE THREAD

**Issue by imn00133** [imn00133/BeerNode#88]
맛을 단계별로 표현하자.
- 스케일바. or radio button 등등
  - select widget
- 맛에 대한 항목?
  - @jeff8287 항목 코멘트로 남기기

**Comment by jeff8287** [comment]
![image](https://user-images.githubusercontent.com/76732738/109382988-05079300-7927-11eb-9a16-05dd6812aa13.png)
![image](https://user-images.githubusercontent.com/76732738/109383122-aa226b80-7927-11eb-9e56-d281a547dabd.png)
![image](https://user-images.githubusercontent.com/76732738/109383128-bad2e180-7927-11eb-80ea-2e13321f6779.png)
처럼 나타내거나

![image](https://user-images.githubusercontent.com/76732738/109383053-4ef07900-7927-11eb-8850-2bfc4d55da1b.png)
에 있는 맛, 향, 질감을 나타내는 표현을 많이 제시해 사용자가 토글 등으로 선택할 수 있게 하거나(Untappd에서 이렇게 하는중)

구체적인건 context에 적게 하고 외관, 향, 마우스필, 맛, 총평만 0.0~5.0의 rating으로 나타낼 수 있게 하는 방안 등이 있을 것 같습니다.

**Comment by imn00133** [comment]
2번 사진으로 하고, 우선적으로 아래 스케일 바를 만들도록 한다.
- 게시물에 column추가
